### ISSUE TITLE
Default values for INSTALL and CLEAR?

### ISSUE THREAD

**Issue by ThorKn** [sea212/QuantumRisc-VM-Build-Tools#2]
We should discuss the default values of the INSTALL and CLEAR values in each install-script.
In my opinion they should be set to TRUE by default.

**Comment by sea212** [comment]
When I designed the scripts I deliberately decided against setting install (and clear) to true for the following reason:
If someone executes those scripts naively or even accidentally and the default behaviour is to install the built files, eventual previously existing local versions are overwritten. In other words, by using this default settings, changes are made to the system by default.
With the current default configurations, no changes to the system (expect the creation of a sub folder and further folders and files within it) are applied. If a user decides he wants local changes in form of newly installed files, he explicitly has to indicate it.

The riscv-tools scripts mark an exception, because the overlying build scripts automatically build and install the files. Therefore no install flag is available (this will probably change in the future versions of this project).

Since I decided against installing the tools by default, clearing the build folder consequently is also deactivated by default. Clearing the build folder without installing it is obviously pointless, because to the user it would appear as the script did nothing, because the only folder it created during its execution was removed again.

Please share your thoughts.
