### ISSUE TITLE
GDB and Python

### ISSUE THREAD

**Issue by ThorKn** [sea212/QuantumRisc-VM-Build-Tools#68]
Today i tried to extend the functionality for the (riscv-)GDB with the following project:
https://github.com/cyrus-and/gdb-dashboard
For running this dashboard, the GDB must have Python support enabled (done while compiling the GDB). 

Issue:
The actual (riscv-)GDB build does not support Python.
 
Reproduce:
start (riscv-)GDB and try to run Python.
```
$ riscv64-unknown-elf-gdb
(gdb) py print("hello")
Python scripting is not supported in this copy of GDB.
```

Possible hint:
https://github.com/riscv/riscv-gnu-toolchain/issues/722

**Comment by ThorKn** [comment]
Further comments:

I see this not as an high priority error in the VM. It is a "nice to have" for development in C. And it's kind of standard to have Python scripting enabled in GDB.

It might become important during the QuantumRisc project to "pimp" the GDB. Maybe for measuring or counting cycles and instructions or such.

The gdb-dashboard does not have to be part of the VM. Developers should only be able to install it themself.

**Comment by sea212** [comment]
This can be worked around by installing the apt package _python-is-python3_. The package is installed automatically since commit [07acf2c03d3c96f0ba85c9aaf206f43fb76611a9](https://github.com/sea212/QuantumRisc-VM-Build-Tools/commit/07acf2c03d3c96f0ba85c9aaf206f43fb76611a9#diff-c90924819df3b725137c215f1c49d427b6335744aea91ec59f07f0ffee64f799R22). To take effect during the build of riscv-gdb, the operator must execute _build_tools/install_build_essentials.sh_ before building gdb. To reduce the margin of error, I'm going to add _python-is-python3_ to _build_tools/riscv_tools/install_riscv_essentials.sh_
